### PR TITLE
stop requiring attr(xattr)

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Latest xattr dropped xattr bits because they are in glibc.

Fixes: https://github.com/rpm-software-management/librepo/issues/121
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@rh-atomic-bot r+

**Comment by ignatenkobrain** [comment]
ping @dmach

**Comment by ignatenkobrain** [comment]
ping @dmach

**Comment by ignatenkobrain** [comment]
ping @dmach

**Comment by ignatenkobrain** [comment]
ping @dmach

**Comment by Conan-Kudo** [comment]
This can be closed, since this change was integrated into librepo already in 1dff9c2c8271ba7019b9a9a4d3612b6d4ff86b2b.

**Pull request closed without merging**
