### PR TITLE
Link against libssl

### PR DESCRIPTION
**Pull request by bgamari**
checksum.c clearly depends upon OpenSSL's EVP implementation. Previously this would result in undefined symbols at runtime.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This fixed my build for Mageia 5/Cauldron 👍

**Comment by cgwalters** [comment]
Is your build still fixed with only `-lcrypto`?

**Comment by cgwalters** [comment]
@Conan-Kudo :arrow_up:

**Comment by Conan-Kudo** [comment]
@cgwalters Looking into it. I need to make some adjustments to use libcrypto instead of this patch.

**Comment by cgwalters** [comment]
The reason I'm talking about this is `libcrypto` is the sane part of OpenSSL, and there's really reason for librepo itself to directly need TLS - that comes from curl.

**Comment by Tojaj** [comment]
Fixed, could someone of you test this on a system where the previous builds failed?

**Comment by Conan-Kudo** [comment]
The fix to use libcrypto works perfectly on Mageia 5 and Cauldron.

**Comment by Tojaj** [comment]
@Conan-Kudo :+1:

**Pull request closed without merging**
