### PR TITLE
Add librepo.spec file

### PR DESCRIPTION
**Pull request by jrohel**
Taken from dis-git.
Platform-python stuff removed.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Ah, also remove platform-python stuff from spec file.. It is totally Fedora's downstream part.

**Comment by jrohel** [comment]
OK. I removed platform-python stuff and changelog.

**Comment by Conan-Kudo** [comment]
Why are we doing this?

**Comment by jrohel** [comment]
We want to use the same work flow as for DNF. That means librepo.spec file will be in upstream.
Last changes of DNF needs last version of librepo. We want to track requested version on the time of PR.

**Comment by ignatenkobrain** [comment]
I've pushed it to master, but: @jrohel we don't use librepo.spec from upstream in CI, so whatever you will make here will not affect nightlies / CI...

**Pull request closed without merging**
