### PR TITLE
Drop Python 2 support

### LINKED ISSUE #183: Remove Python 2 specific code / build steps

### PR DESCRIPTION
**Pull request by dralley**
closes #183

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
@dralley Can you rebase this?

**Comment by dralley** [comment]
@Conan-Kudo Yes, done.

**Comment by dralley** [comment]
@Conan-Kudo Like w/ the other repos, I didn't touch the spec file.  Not sure what if anything needs to be changed there.

**Comment by Conan-Kudo** [comment]
@dralley All Python 2 support needs to be removed from the spec. Please send a PR to adjust the spec to disable building Python bindings on RHEL 7 and older.

**Pull request merged**
